### ISSUE TITLE
Provide NuGet package?

### ISSUE THREAD

**Issue by andreypesoshin** [BredStik/OwinSelfHosting#1]
I just found your project that solves my problem of supporting Castle with WebApi2 controllers self-hosting with OWIN.
Unfortunately the only option I have right now is to add an existing csproj to my solution and therefore to lose compatibility with further changes.

Providing a NuGet OwinSelfHosting package is highly appreciated!

**Comment by BredStik** [comment]
Thanks for your interest in this small sample.  What part of this project would you like to see packaged as a NuGet package?   I assume you're talking about DependencyResolverScopeMiddleware.cs, WindsorDependencyResolver.cs and WindsorDependencyScope.cs (and possibly a few extensions)?  

As I do not plan to really maintain this project, I would suggest you bring over those classes in your project and maintain them as Windsor gets updated, etc.

But I can always create a small NuGet package that encapsulates the functionality if you wish.

**Comment by BredStik** [comment]
Created a nuget package and usage instructions in readme file.  Let me know if it helps!

https://www.nuget.org/packages/OWIN.Windsor.DependencyResolverScopeMiddleware/0.9.5676.18344
https://github.com/BredStik/OwinSelfHosting/blob/master/README.md

Enjoy!
